services:
  plugin-test:
    build:
      dockerfile: server/Dockerfile
    volumes:
      - server:/server
    ports:
      - "25565:25565"
      - "5005:5005"
    stdin_open: true
    tty: true
    network_mode: host

volumes:
  server: