name: Build all changed projects

on:
  push:
    branches:
      - master
    paths:
      - di-framework/**
      - staffmanager-core/**
      - yukikase-lib/**
      - .github/workflows/**

jobs:
  determine_versions:
    runs-on: ubuntu-latest
    outputs:
      di-framework-version: ${{ steps.versions.outputs.di-framework-version }}
      yukikase-lib-version: ${{ steps.versions.outputs.yukikase-lib-version }}
      staffmanager-core-version: ${{ steps.versions.outputs.staffmanager-core-version }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install -r scripts/semver_tool/requirements.txt

      # TOOD: add creation of rntmp folder to the python script
      - name: Determine versions
        id: versions
        run: |
          mkdir rntmp
          versions=$(python scripts/semver_tool/semver_tool.py -e dev di-framework yukikase-lib staffmanager-core)
          
          if [ -z "$versions" ]; then
            exit 78
          fi
          
          IFS=$'\n'
          for item in $versions; do
            IFS=':' 
            read -r project version <<<"$item"
            IFS=$'\n'
            if [ "$project" = "di-framework" ]; then
              echo "di-framework-version=$version" >> $GITHUB_OUTPUT
            elif [ "$project" = "yukikase-lib" ]; then
              echo "yukikase-lib-version=$version" >> $GITHUB_OUTPUT
            elif [ "$project" = "staffmanager-core" ]; then
              echo "staffmanager-core-version=$version" >> $GITHUB_OUTPUT
            fi
          done

      - name: Upload version file
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: version.yaml

      - name: Upload release notes
        uses: actions/upload-artifact@v4
        with:
          name: release_notes
          path: rntmp/
  
  update_versions:
    runs-on: ubuntu-latest
    needs: determine_versions
    outputs:
      changes: ${{ steps.changes.outputs.changes }}

    steps:
      - uses: actions/checkout@v4

      - name: get projects to build
        id: changes
        run: |
          changes=()
          if [ -n "${{ needs.determine_versions.outputs.di-framework-version }}" ]; then
            changes=("${changes[@]}" "com.yukikase:di-framework")
          fi
          if [ -n "${{ needs.determine_versions.outputs.yukikase-lib-version }}" ]; then
            changes=("${changes[@]}" "com.yukikase:yukikase-lib")
          fi
          if [ -n "${{ needs.determine_versions.outputs.staffmanager-core-version }}" ]; then
            changes=("${changes[@]}" "com.yukikase:staffmanager.core")
          fi
          changes=$(IFS=, ; echo "${changes[*]}") echo "changes=$changes"
          echo "changes=$(printf ",%s" "${changes[@]}")" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    needs:
      - update_versions
      - determine_versions

    steps:
      - uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Update versions
        run: |
          if [ -n "${{ needs.determine_versions.outputs.di-framework-version }}" ]; then
            mvn versions:set-property -Dproperty=di-framework.version -DnewVersion=${{ needs.determine_versions.outputs.di-framework-version }}
          fi
          if [ -n "${{ needs.determine_versions.outputs.yukikase-lib-version }}" ]; then
            mvn versions:set-property -Dproperty=yukikase-lib.version -DnewVersion=${{ needs.determine_versions.outputs.yukikase-lib-version }}
          fi
          if [ -n "${{ needs.determine_versions.outputs.staffmanager-core-version }}" ]; then
            mvn versions:set-property -Dproperty=staffmanager.core.version -DnewVersion=${{ needs.determine_versions.outputs.staffmanager-core-version }}
          fi
          mvn versions:commit

      - name: Authenticate to GitHub Packages
        run: echo "<settings><servers><server><id>3-github</id><username>${{ github.actor }}</username><password>${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: build and deploy all changed projects
        run: mvn --batch-mode deploy -pl ${{ needs.update_versions.outputs.changes }}

      - name: Upload pom
        uses: actions/upload-artifact@v4
        with:
          name: pom
          path: pom.xml

      - name: Upload di-framework jar
        if: ${{ needs.determine_versions.outputs.di-framework-version }}
        uses: actions/upload-artifact@v4
        with:
          name: di-framework-jar
          path: di-framework/target/*.jar

      - name: Upload yukikase-lib jar
        if: ${{ needs.determine_versions.outputs.yukikase-lib-version }}
        uses: actions/upload-artifact@v4
        with:
          name: yukikase-lib-jar
          path: yukikase-lib/target/*.jar

      - name: Upload staffmanager-core jar
        if: ${{ needs.determine_versions.outputs.staffmanager-core-version }}
        uses: actions/upload-artifact@v4
        with:
          name: staffmanager-core-jar
          path: staffmanager/core/target/*.jar

  release:
    runs-on: ubuntu-latest
    needs:
      - determine_versions
      - build
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Download version file
        uses: actions/download-artifact@v4
        with:
          name: version
          path: ./

      - name: Download pom.xml
        uses: actions/download-artifact@v4
        with:
          name: pom
          path: ./

      - name: Commit version file and pom
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add version.yaml pom.xml
          git commit -m "chore: update version file and pom"
          git push

      - name: get workflow folder contents
        run: |
          ls -al ./.github/workflows/

  release-di-framework:
    permissions:
      contents: write
    needs:
      - determine_versions
      - release
    if: ${{ needs.determine_versions.outputs.di-framework-version }}
    uses: ./.github/workflows/release_template.yml
    with:
      env: 'dev'
      version: ${{ needs.determine_versions.outputs.di-framework-version }}
      project: 'di-framework'

  release-yukikase-lib:
    permissions:
      contents: write
    needs:
      - determine_versions
      - release
    if: ${{ needs.determine_versions.outputs.yukikase-lib-version }}
    uses: ./.github/workflows/release_template.yml
    with:
      env: 'dev'
      version: ${{ needs.determine_versions.outputs.yukikase-lib-version }}
      project: 'yukikase-lib'

  release-staffmanager-core:
    permissions:
      contents: write
    needs:
      - determine_versions
      - release
    if: ${{ needs.determine_versions.outputs.staffmanager-core-version }}
    uses: ./.github/workflows/release_template.yml
    with:
      env: 'dev'
      version: ${{ needs.determine_versions.outputs.staffmanager-core-version }}
      project: 'staffmanager-core'
      path: 'staffmanager/core'
