name: Build all changed projects

on:
  push:
    branches:
      - master
    paths:
      - di-framework/**
      - staffmanager-core/**
      - yukikase-lib/**
      - .github/workflows/**

jobs:
  get_changed_projects:
    runs-on: ubuntu-latest
    outputs:
      di-framework: ${{ steps.changes.outputs.di-framework }}
      yukikase-lib: ${{ steps.changes.outputs.yukikase-lib }}
      staffmanager-core: ${{ steps.changes.outputs.staffmanager-core }}

    steps:
      - uses: actions/checkout@v4

      - name: Get changed projects
        id: changes
        run: |
          echo "di-framework=$(git diff --quiet ${{ github.event.after }} ${{ github.event.before }} -- di-framework || echo 1)" >> $GITHUB_OUTPUT
          echo "yukikase-lib=$(git diff --quiet ${{ github.event.after }} ${{ github.event.before }} -- yukikase-lib || echo 1)" >> $GITHUB_OUTPUT
          echo "staffmanager-core=$(git diff --quiet ${{ github.event.after }} ${{ github.event.before }} -- staffmananger-core || echo 1)" >> $GITHUB_OUTPUT

  update_versions:
    runs-on: ubuntu-latest
    needs: get_changed_projects
    outputs:
      di-framework-version: ${{ steps.di-framework.outputs.version }}
      yukikase-lib-version: ${{ steps.yukikase-lib.outputs.version }}
      staffmanager-core-version: ${{ steps.staffmanager-core.outputs.version }}
      changes: ${{ steps.changes.outputs.changes }}

    steps:
      - uses: actions/checkout@v4

      - name: update version of di-framework
        id: di-framework
        if: ${{ needs.get_changed_projects.outputs.di-framework }}
        uses: ./.github/workflows/versioning_template.yml
        with:
          project: di-framework
          env: 'dev'

      - name: update version of yukikase-lib
        id: yukikase-lib
        if: ${{ needs.get_changed_projects.outputs.yukikase-lib }}
        uses: ./.github/workflows/versioning_template.yml
        with:
          project: yukikase-lib
          env: 'dev'

      - name: update version of staffmanager.core
        id: staffmanager-core
        if: ${{ needs.get_changed_projects.outputs.staffmanager-core }}
        uses: ./.github/workflows/versioning_template.yml
        with:
          project: staffmanager.core
          env: 'dev'

      - name: get projects to build
        id: changes
        run: |
          changes=()
          if [ -n ${{ steps.di-framework.outputs.needs-release }} ]; then
            changes=("${changes[@]}" "com.yukikase:di-framework")
          fi
          if [ -n ${{ steps.yukikase-lib.outputs.needs-release }} ]; then
            changes=("${changes[@]}" "com.yukikase:yukikase-lib")
          fi
          if [ -n ${{ steps.staffmanager-core.outputs.needs-release }} ]; then
            changes=("${changes[@]}" "com.yukikase:staffmanager.core")
          fi
          changes=$(IFS=, ; echo "${changes[*]}") echo "changes=$changes"
          echo "changes=$(printf ",%s" "${changes[@]}")" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs:
      - update_versions
      - get_changed_projects
    if: ${{ needs.update_versions.outputs.changes }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Authenticate to GitHub Packages
        run: echo "<settings><servers><server><id>3-github</id><username>${{ github.actor }}</username><password>${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: build and deploy all changed projects
        run: mvn --batch-mode deploy -pl ${{ needs.update_versions.outputs.changes }} -amd

      - name: Upload di-framework jar
        if: ${{ needs.get_changed_projects.outputs.di-framework }}
        uses: actions/upload-artifact@v4
        with:
          name: di-framework-jar
          path: di-framework/target/*.jar

      - name: Upload yukikase-lib jar
        if: ${{ needs.get_changed_projects.outputs.yukikase-lib }}
        uses: actions/upload-artifact@v4
        with:
          name: yukikase-lib-jar
          path: yukikase-lib/target/*.jar

      - name: Upload staffmanager-core jar
        fi: ${{ needs.get_changed_projects.outputs.staffmanager-core }}
        uses: actions/upload-artifact@v4
        with:
          name: staffmanager-core-jar
          path: staffmanager/core/target/*.jar

  release:
    runs-on: ubuntu-latest
    needs:
      - update_versions
      - build
    permissions:
      contents: write
      packages: write

    steps:
      - name: Download version file
        uses: actions/download-artifact@v4
        with:
          name: version
          path: ./

      - name: Commit version file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add version.yaml
          git commit -m "chore: update version file"
          git push

      - name: Release di framework
        if: ${{ needs.update_versions.outputs.di-framework-version }}
        uses: ./.github/workflows/release_template.yml
        with:
          env: 'dev'
          version: ${{ needs.update_versions.outputs.di-framework-version }}
          project: 'di-framework'

      - name: Release yukikase lib
        if: ${{ needs.update_versions.outputs.yukikase-lib-version }}
        uses: ./.github/workflows/release_template.yml
        with:
          env: 'dev'
          version: ${{ needs.update_versions.outputs.yukikase-lib-version }}
          project: 'yukikase-lib'

      - name: Release staffmanager core
        if: ${{ needs.update_versions.outputs.staffmanager-core-version }}
        uses: ./.github/workflows/release_template.yml
        with:
          env: 'dev'
          version: ${{ needs.update_versions.outputs.staffmanager-core-version }}
          project: 'staffmanager-core'
          path: 'staffmanager/core'
