name: Build all changed projects

on:
  push:
    branches:
      - master
    paths:
      - di-framework/**
      - staffmanager-core/**
      - yukikase-lib/**
      - .github/workflows/**

jobs:
  get_changed_projects:
    runs-on: ubuntu-latest
    outputs:
      di-framework: ${{ steps.changes.outputs.di-framework }}
      yukikase-lib: ${{ steps.changes.outputs.yukikase-lib }}
      staffmanager-core: ${{ steps.changes.outputs.staffmanager-core }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed projects
        id: changes
        run: |
          echo "di-framework=$(git diff --quiet ${{ github.event.after }} ${{ github.event.before }} -- di-framework || echo 1)" >> $GITHUB_OUTPUT
          echo "yukikase-lib=$(git diff --quiet ${{ github.event.after }} ${{ github.event.before }} -- yukikase-lib || echo 1)" >> $GITHUB_OUTPUT
          echo "staffmanager-core=$(git diff --quiet ${{ github.event.after }} ${{ github.event.before }} -- staffmananger-core || echo 1)" >> $GITHUB_OUTPUT

  determine_versions:
    runs-on: ubuntu-latest
    needs: get_changed_projects
    outputs:
      di-framework-version: ${{ steps.versions.outputs.di-framework-version }}
      yukikase-lib-version: ${{ steps.versions.outputs.yukikase-lib-version }}
      staffmanager-core-version: ${{ steps.versions.outputs.staffmanager-core-version }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create project list to determine versions for
        run: |
          projects=""
          if [ -n ${{ needs.get_changed_projects.outputs.di-framework }} ]; then
            projects="$projects di-framework"
          fi
          if [ -n ${{ needs.get_changed_projects.outputs.yukikase-lib }} ]; then
            projects="$projects yukikase-lib"
          fi
          if [ -n ${{ needs.get_changed_projects.outputs.staffmanager-core }} ]; then
            projects="$projects staffmanager-core"
          fi
          echo "projects=$projects" >> $GITHUB_ENV

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install -r scripts/semver_tool/requirements.txt

      - name: Determine versions
        id: versions
        run: |
          versions=$(python scripts/semver_tool/semver_tool.py -e dev ${{ env.projects }})
          
          IFS=$'\n'
          for item in $versions; do
            IFS=':' 
            read -r project version <<<"$item"
            IFS=$'\n'
            if [ $project -eq "di-framework" ]; then
              echo "di-framework-version=$version" >> $GITHUB_OUTPUT
            elif [ $project -eq "yukikase-lib" ]; then
              echo "yukikase-lib-version=$version" >> $GITHUB_OUTPUT
            elif [ $project -eq "staffmanager-core" ]; then
              echo "staffmanager-core-version=$version" >> $GITHUB_OUTPUT
            fi
          done
  
  update_versions:
    runs-on: ubuntu-latest
    needs: determine_versions
    outputs:
      changes: ${{ steps.changes.outputs.changes }}

    steps:
      - uses: actions/checkout@v4

      - name: get projects to build
        id: changes
        run: |
          changes=()
          if [ -n ${{ needs.determine_versions.outputs.di-framework-version }} ]; then
            changes=("${changes[@]}" "com.yukikase:di-framework")
          fi
          if [ -n ${{ needs.determine_versions.outputs.yukikase-lib-version }} ]; then
            changes=("${changes[@]}" "com.yukikase:yukikase-lib")
          fi
          if [ -n ${{ needs.determine_versions.outputs.staffmanager-core-version }} ]; then
            changes=("${changes[@]}" "com.yukikase:staffmanager.core")
          fi
          changes=$(IFS=, ; echo "${changes[*]}") echo "changes=$changes"
          echo "changes=$(printf ",%s" "${changes[@]}")" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs:
      - update_versions
      - get_changed_projects
      - determine_versions
    if: ${{ needs.update_versions.outputs.changes }}

    steps:
      - uses: actions/checkout@v4

      - name: Download pom.xml
        if: ${{ needs.determine_versions.outputs.di-framework-version }}
        uses: actions/download-artifact@v4
        with:
          name: di-framework-pom
          path: di-framework/

      - name: Download pom.xml
        if: ${{ needs.determine_versions.outputs.yukikase-lib-version }}
        uses: actions/download-artifact@v4
        with:
          name: yukikase-lib-pom
          path: yukikase-lib/

      - name: Download pom.xml
        if: ${{ needs.determine_versions.outputs.staffmanager-core-version }}
        uses: actions/download-artifact@v4
        with:
          name: staffmanager-core-pom
          path: staffmanager/core/

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Authenticate to GitHub Packages
        run: echo "<settings><servers><server><id>3-github</id><username>${{ github.actor }}</username><password>${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: build and deploy all changed projects
        run: mvn --batch-mode deploy -pl ${{ needs.update_versions.outputs.changes }} -amd

      - name: Upload di-framework jar
        if: ${{ needs.get_changed_projects.outputs.di-framework }}
        uses: actions/upload-artifact@v4
        with:
          name: di-framework-jar
          path: di-framework/target/*.jar

      - name: Upload yukikase-lib jar
        if: ${{ needs.get_changed_projects.outputs.yukikase-lib }}
        uses: actions/upload-artifact@v4
        with:
          name: yukikase-lib-jar
          path: yukikase-lib/target/*.jar

      - name: Upload staffmanager-core jar
        if: ${{ needs.get_changed_projects.outputs.staffmanager-core }}
        uses: actions/upload-artifact@v4
        with:
          name: staffmanager-core-jar
          path: staffmanager/core/target/*.jar

  release:
    runs-on: ubuntu-latest
    needs:
      - determine_versions
      - build
    permissions:
      contents: write
      packages: write

    steps:
      - name: Download version file
        uses: actions/download-artifact@v4
        with:
          name: version
          path: ./

      - name: Commit version file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add version.yaml
          git commit -m "chore: update version file"
          git push

      - name: Release di framework
        if: ${{ needs.determine_versions.outputs.di-framework-version }}
        uses: ./.github/workflows/release_template.yml
        with:
          env: 'dev'
          version: ${{ needs.determine_versions.outputs.di-framework-version }}
          project: 'di-framework'

      - name: Release yukikase lib
        if: ${{ needs.determine_versions.outputs.yukikase-lib-version }}
        uses: ./.github/workflows/release_template.yml
        with:
          env: 'dev'
          version: ${{ needs.determine_versions.outputs.yukikase-lib-version }}
          project: 'yukikase-lib'

      - name: Release staffmanager core
        if: ${{ needs.determine_versions.outputs.staffmanager-core-version }}
        uses: ./.github/workflows/release_template.yml
        with:
          env: 'dev'
          version: ${{ needs.determine_versions.outputs.staffmanager-core-version }}
          project: 'staffmanager-core'
          path: 'staffmanager/core'
