name: Release di-framework maven package

on:
  workflow_dispatch:
    inputs:
      env:
        default: 'main'
        required: true
        type: string
        options:
          - 'main'
          - 'rc'
          - 'dev'
        description: The environment type pipeline is run in
  push:
    branches:
      - master
    paths:
      - 'di-framework/**'
      - '.github/workflows/di-framework.yml'
      - '.github/workflows/java_release_template.yml'

jobs:
  determine_env:
    runs-on: ubuntu-latest

    steps:
      - name: Determine environment
        id: environment
        run: |
          if [ "${{ github.event_name }}" -eq "workflow_dispatch" ]; then
            echo "env=${{ github.event.inputs.env }}" >> $GITHUB_ENV
          else
            echo "env=dev" >> $GITHUB_ENV
          fi

    outputs:
      env: ${{ env.env }}

  release:
    permissions:
      contents: write
      packages: write
    needs: determine_env
    uses: ./.github/workflows/java_release_template.yml
    with:
      env: ${{ needs.determine_env.outputs.env }}
      project: 'di-framework'
